export interface IncidentOverview {
  id: number;
  title: string;
  type: string;
  severity: string;
  summary: string;
  status: string;
  impactStartedAt: string;
  lead: string;
  leadAvatar: string;
}

export interface Incident {
  id: number;
  reference: number | null;
  status: string;
  type: string;
  lead: number | null;
  reporter: number | null;
  reporterName: string;
  leadName: string | null;
  QEName: string | null;
  reporterAvatar: string | null;
  leadAvatar: string | null;
  QEAvatar: string | null;
  title: string;
  summary: string;
  severity: string;
  impact: string | null;
  postMortem: string | null;
  impactStartedAt: string | null;
  impactStoppedAt: string | null;
  reportedAt: string | null;
  identifiedAt: string | null;
  fixedAt: string | null;
  resolvedAt: string | null;
  documentationAt: string | null;
  inReviewAt: string | null;
  closedAt: string | null;
  acceptedAt: string | null;
  declinedAt: string | null;
  mergedAt: string | null;
  canceledAt: string | null;
  triagedBy: string | null;
  treatment: string | null;
  mitigator: string | null;
  slackChannel: string | null;
  relatedIncident: number | null;
  incidentSource: string | null;
  threadOnSlack: string | null;
  cleanedUpAt: string | null;
  monitoredAt: string | null;
  investigatingAt: string | null;
  fixingAt: string | null;
  monitoringAt: string | null;
  cleaningUpAt: string | null;
  postToStatusPage: boolean | null;
  documentedAt: string | null;
  reviewedAt: string | null;
  category: string | null;
  qe: number | null;
  products: Record<number, string>;
  areas: Record<number, string>;
  causes: Record<number, string>;
  faultySystems: Record<number, string>;
  performanceIndicators: Record<number, string>;
}
